/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.Treasure;
/**
 *
 * @author Juanki1
 */
public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel;
    private boolean selected=false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    public void setSelected(boolean seleccion){
        
        selected=seleccion;
        
    }
    
    public boolean isSelected(){
    
        return selected;
    
    }
    
    public Treasure getTreasure(){
        
        return treasureModel;
        
    }
    
    public void setTreasure (Treasure t) {
        treasureModel = t;
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUITreasures/"+treasureModel.getName()+".jpg")));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        if(isSelected()){
            
            this.setSelected(false);
            jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            
        }
        
        else{
        
            jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
            this.setSelected(true);
            
        } 
            
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

